add wave -noupdate -divider memory
add wave -noupdate -group ft0ch0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/write_col_sel(0)
add wave -noupdate -group ft0ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(0)/segx(0)/sadd/oneseg(1)
add wave -noupdate -group ft0ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(0)/segx(1)/sadd/oneseg(1)
add wave -noupdate -group ft0ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(0)/segx(2)/sadd/oneseg(1)
add wave -noupdate -group ft0ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(0)/segx(3)/sadd/oneseg(1)
add wave -noupdate -group ft0ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(0)/segx(4)/sadd/oneseg(1)
add wave -noupdate -group ft0ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(0)/segx(5)/sadd/oneseg(1)
add wave -noupdate -group ft0ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(0)/segx(6)/sadd/oneseg(1)
add wave -noupdate -group ft0ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(0)/segx(7)/sadd/oneseg(1)
add wave -noupdate -group ft0ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(0)/segx(8)/sadd/oneseg(1)
add wave -noupdate -group ft1ch0 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/write_col_sel(1)
add wave -noupdate -group ft1ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(1)/segx(0)/sadd/oneseg(1)
add wave -noupdate -group ft1ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(1)/segx(1)/sadd/oneseg(1)
add wave -noupdate -group ft1ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(1)/segx(2)/sadd/oneseg(1)
add wave -noupdate -group ft1ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(1)/segx(3)/sadd/oneseg(1)
add wave -noupdate -group ft1ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(1)/segx(4)/sadd/oneseg(1)
add wave -noupdate -group ft1ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(1)/segx(5)/sadd/oneseg(1)
add wave -noupdate -group ft1ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(1)/segx(6)/sadd/oneseg(1)
add wave -noupdate -group ft1ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(1)/segx(7)/sadd/oneseg(1)
add wave -noupdate -group ft1ch0 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(0)/PEs/gen_seg(1)/segx(8)/sadd/oneseg(1)
add wave -noupdate -group ft0ch1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/write_col_sel(0)
add wave -noupdate -group ft0ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(0)/segx(0)/sadd/oneseg(1)
add wave -noupdate -group ft0ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(0)/segx(1)/sadd/oneseg(1)
add wave -noupdate -group ft0ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(0)/segx(2)/sadd/oneseg(1)
add wave -noupdate -group ft0ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(0)/segx(3)/sadd/oneseg(1)
add wave -noupdate -group ft0ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(0)/segx(4)/sadd/oneseg(1)
add wave -noupdate -group ft0ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(0)/segx(5)/sadd/oneseg(1)
add wave -noupdate -group ft0ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(0)/segx(6)/sadd/oneseg(1)
add wave -noupdate -group ft0ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(0)/segx(7)/sadd/oneseg(1)
add wave -noupdate -group ft0ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(0)/segx(8)/sadd/oneseg(1)
add wave -noupdate -group ft1ch1 /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/write_col_sel(1)
add wave -noupdate -group ft1ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(1)/segx(0)/sadd/oneseg(1)
add wave -noupdate -group ft1ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(1)/segx(1)/sadd/oneseg(1)
add wave -noupdate -group ft1ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(1)/segx(2)/sadd/oneseg(1)
add wave -noupdate -group ft1ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(1)/segx(3)/sadd/oneseg(1)
add wave -noupdate -group ft1ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(1)/segx(4)/sadd/oneseg(1)
add wave -noupdate -group ft1ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(1)/segx(5)/sadd/oneseg(1)
add wave -noupdate -group ft1ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(1)/segx(6)/sadd/oneseg(1)
add wave -noupdate -group ft1ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(1)/segx(7)/sadd/oneseg(1)
add wave -noupdate -group ft1ch1 -radix decimal /tb_pulp/i_dut/soc_domain_i/pulp_soc_i/i_pec_top/pec_accellerator_i/gen_PE(1)/PEs/gen_seg(1)/segx(8)/sadd/oneseg(1)
